* try false + exit in script * disable broken blocks_baseline + early errexit

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -4,9 +4,33 @@ os: linux
 matrix:
   include:
   - name: baseline
-    before_script:
+    before_script: # non-zero exit code: stops build
     - bash --version 
     - echo "-- started before_script"
+    - ( exit 0 )
+    - echo "-- after exit 0"
+    - ( true )
+    - echo "-- after true"
+    #- ( exit 1 ) # <--- stops build (trusty)
+    #- echo "-- after exit 1"
+    - ( false )
+    - echo "-- after false"
+    - echo "-- finish before_script"
+    script: # non-zero exit code: fails build
+    - echo "-- start script"
+    - |
+      echo "-- start block"
+      echo "-- finish block"
+    - echo "-- finish script"
+    after_script: # non-zero exit code: no effect
+    - echo "-- full build completed"
+  - name: baseline exit in script
+    before_script: # non-zero exit code: stops build
+    - bash --version 
+    - echo "-- started before_script"
+    - echo "-- finish before_script"
+    script: # non-zero exit code: fails build
+    - echo "-- start script"
     - ( exit 0 )
     - echo "-- after exit 0"
     - ( true )
@@ -15,22 +39,33 @@ matrix:
     - echo "-- after exit 1"
     - ( false )
     - echo "-- after false"
-    - echo "-- finish before_script"
-    script:
-    - echo "-- start script"
-    - |
-      echo "-- start block"
-      echo "-- finish block"
     - echo "-- finish script"
-    after_script:
-    - echo "-- start after_script"
-    - echo "-- finish after_script"
-  - name: blocks_baseline
-    before_script:
-    - bash --version 
-    - echo "-- started before_script"
-    - echo "-- finish before_script"
-    script:
+    after_script: # non-zero exit code: no effect
+    - echo "-- full build completed"
+#  - name: blocks_baseline # broken, should fail
+#    before_script: # non-zero exit code: stops build
+#    - bash --version 
+#    script: # non-zero exit code: fails build
+#    - echo "-- start script"
+#    - |
+#      echo "-- start block"
+#      ( exit 0 )
+#      echo "-- after exit 0"
+#      ( true )
+#      echo "-- after true"
+#      ( exit 1 )
+#      echo "-- after exit 1"
+#      ( false )
+#      echo "-- after false"
+#      echo "-- finish block"
+#    - echo "-- finish script"
+#    after_script: # non-zero exit code: no effect
+#    - echo "-- full build completed"
+  - name: blocks_errexit
+    before_script: # non-zero exit code: stops build
+    - bash --version
+    - set -e # early errexit
+    script: # non-zero exit code: fails build
     - echo "-- start script"
     - |
       echo "-- start block"
@@ -44,10 +79,7 @@ matrix:
       echo "-- after false"
       echo "-- finish block"
     - echo "-- finish script"
-    after_script:
-    - echo "-- start after_script"
-    - echo "-- finish after_script"
-
-
+    after_script: # non-zero exit code: no effect
+    - echo "-- full build completed"
 
 
